road_network_1 = {
    "size": (10, 19),
    "roads": [
        {"position": (0, 0), "size": (10, 1)},
        {"position": (0, 3), "size": (10, 1)},
        {"position": (0, 7), "size": (10, 1)},
        {"position": (0, 11), "size": (10, 1)},
        {"position": (0, 15), "size": (10, 1)},
        {"position": (0, 18), "size": (10, 1)},
        {"position": (1, 0), "size": (1, 4)},
        {"position": (1, 7), "size": (1, 12)},
        {"position": (4, 0), "size": (2, 19)},
        {"position": (8, 0), "size": (1, 19)},
    ],
    "intersections": [
        {"position": (4, 0), "size": (1, 1)},
        {"position": (4, 3), "size": (1, 1)},
        {"position": (4, 7), "size": (1, 1)},
        {"position": (4, 11), "size": (1, 1)},
        {"position": (4, 15), "size": (1, 1)},
        {"position": (4, 18), "size": (1, 1)},
    ],
    "obstacles": [
        {"type": "wall", "position": (0, 1), "size": (1, 2)},
        {"type": "wall", "position": (0, 4), "size": (1, 3)},
        {"type": "wall", "position": (0, 8), "size": (1, 3)},
        {"type": "wall", "position": (0, 12), "size": (1, 3)},
        {"type": "wall", "position": (0, 16), "size": (1, 2)},
        {"type": "wall", "position": (2, 1), "size": (2, 2)},
        {"type": "wall", "position": (2, 4), "size": (2, 3)},
        {"type": "wall", "position": (2, 8), "size": (2, 3)},
        {"type": "wall", "position": (2, 12), "size": (2, 3)},
        {"type": "wall", "position": (2, 16), "size": (2, 2)},
        {"type": "wall", "position": (6, 1), "size": (2, 2)},
        {"type": "wall", "position": (6, 4), "size": (2, 3)},
        {"type": "wall", "position": (6, 8), "size": (2, 3)},
        {"type": "wall", "position": (6, 12), "size": (2, 3)},
        {"type": "wall", "position": (6, 16), "size": (2, 2)},
        {"type": "wall", "position": (9, 1), "size": (1, 2)},
        {"type": "wall", "position": (9, 4), "size": (1, 3)},
        {"type": "wall", "position": (9, 8), "size": (1, 3)},
        {"type": "wall", "position": (9, 12), "size": (1, 3)},
        {"type": "wall", "position": (9, 16), "size": (1, 2)},
    ],
}
